# Generated by Django 5.1.15 on 2026-07-09 09:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("image_url", models.CharField(blank=True, default="", max_length=300)),
                (
                    "dealer_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("passive", "معطّل")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("require_player_id", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "games",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PriceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "dollar_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_groups",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "price_groups",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "recommended_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("kupur", models.CharField(blank=True, default="", max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("passive", "معطّل"),
                            ("sale_paused", "بيع موقوف مؤقتاً"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("is_parcali", models.BooleanField(default=False)),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("manual", "يدوي"), ("auto", "تلقائي")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.game",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
