# Generated by Django 5.1.15 on 2026-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="kurulu_sale",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="sms_template",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="toplu_sale",
            field=models.BooleanField(default=False),
        ),
    ]
