# Generated by Django 5.1.15 on 2026-07-11 21:12

import catalog.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_agentmargin"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=catalog.models._uuid_hex,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("image_url", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("require_player_id", models.BooleanField(default=False)),
                ("kurulu_sale", models.BooleanField(default=True)),
                ("toplu_sale", models.BooleanField(default=False)),
                ("sms_template", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "library_games",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="master_library_uuid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.CreateModel(
            name="LibraryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=catalog.models._uuid_hex,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "suggested_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("kupur", models.CharField(blank=True, default="", max_length=60)),
                ("is_parcali", models.BooleanField(default=False)),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("manual", "يدوي"), ("auto", "تلقائي")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.librarygame",
                    ),
                ),
            ],
            options={
                "db_table": "library_products",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
