# Generated by Django 5.1.15 on 2026-07-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_librarygame_game_master_library_uuid_libraryproduct"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="providers.provider",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="provider_package_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
