# Generated by Django 5.1.15 on 2026-07-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_provider_product_provider_package_id"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="provider_alt1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_alt1",
                to="providers.provider",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="provider_alt2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_alt2",
                to="providers.provider",
            ),
        ),
    ]
