# Generated by Django 5.1.4 on 2026-07-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_provider_alt1_product_provider_alt2'),
        ('core', '0011_tenant_theme_config'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=120)),
                ('package_name', models.CharField(blank=True, default='', max_length=200)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='providers.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='core.tenant')),
            ],
            options={
                'db_table': 'product_links',
                'ordering': ['product_id', 'provider_id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'provider'), name='uniq_product_provider_link')],
            },
        ),
    ]
