# Generated by Django 5.1.15 on 2026-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_link_prices_to_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='margin_mode',
            field=models.CharField(blank=True, choices=[('percent', 'نسبة مئوية من التكلفة'), ('fixed', 'مبلغ ثابت فوق التكلفة')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='productprice',
            name='margin_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
