# Generated by Django 5.1.15 on 2026-08-04 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productprice_margin_mode_productprice_margin_value'),
        ('core', '0020_user_dealer_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_price_groups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_price_groups', to='core.tenant')),
            ],
            options={
                'db_table': 'agent_price_groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgentProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.agentpricegroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_prices', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_product_prices', to='core.tenant')),
            ],
            options={
                'db_table': 'agent_product_prices',
            },
        ),
        migrations.AddConstraint(
            model_name='agentpricegroup',
            constraint=models.UniqueConstraint(fields=('agent', 'name'), name='uniq_agent_group_name'),
        ),
        migrations.AddConstraint(
            model_name='agentproductprice',
            constraint=models.UniqueConstraint(fields=('group', 'product'), name='uniq_agent_group_product'),
        ),
    ]
