# Generated by Django 5.1.15 on 2026-07-10 23:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_productprice"),
        ("core", "0002_user_oyun_load_limit_user_price_group"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_no", models.CharField(max_length=20, unique=True)),
                ("player_id", models.CharField(blank=True, default="", max_length=60)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("processing", "قيد التنفيذ"),
                            ("success", "ناجح"),
                            ("cancelled", "ملغى"),
                            ("stuck", "عالق"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "pin_result",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "api_response",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dealer_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="catalog.game",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="catalog.product",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="providers.provider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
