# Generated by Django 5.1.15 on 2026-08-04 23:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_buyer_price(apps, schema_editor):
    """
    الطلبات القديمة بلا وسيط: ما دفعه المشتري هو ما قبضه المتجر.

    بدون هذا يقرأ الوكيل «دفعتَ 0.00» في كل طلب سابق، ويُحسب ربحه من زبونه
    كأنّه اشترى مجّاناً.
    """
    apps.get_model("orders", "Order").objects.update(
        buyer_price=models.F("sell_price"),
        agent_profit=Decimal("0"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_dealer_sell_price_order_dealer_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.RunPython(backfill_buyer_price, migrations.RunPython.noop),
    ]
