# Generated by Django 5.1.15 on 2026-08-15 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_agentpricegroup_agentproductprice_and_more'),
        ('core', '0022_user_internal_supply_allowed'),
        ('orders', '0004_order_agent_order_agent_profit_order_buyer_price'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('dealer', 'client_uuid'), name='uniq_order_client_uuid_per_dealer'),
        ),
    ]
