# Generated by Django 5.1.15 on 2026-08-02 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_user_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'غير مربوط'), ('qr', 'بانتظار مسح الرمز'), ('connecting', 'جارٍ الاتصال'), ('connected', 'متّصل'), ('closed', 'منقطع')], default='idle', max_length=12)),
                ('want', models.CharField(choices=[('none', 'لا شيء'), ('start', 'ابدأ الجلسة'), ('logout', 'اقطع الجلسة')], default='none', max_length=8)),
                ('qr', models.TextField(blank=True, default='')),
                ('device_number', models.CharField(blank=True, default='', max_length=32)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('min_delay', models.PositiveIntegerField(default=4)),
                ('max_delay', models.PositiveIntegerField(default=10)),
                ('batch_size', models.PositiveIntegerField(default=25)),
                ('batch_pause', models.PositiveIntegerField(default=300)),
                ('balance_template', models.TextField(blank=True, default='مرحباً {الاسم} 👋\nدَينك الحالي {الدين} {العملة}.\nنرجو التسديد، وشكراً لتعاملك معنا.\n{المتجر}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='core.tenant')),
            ],
            options={
                'db_table': 'whatsapp_accounts',
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإرسال'), ('sending', 'جارٍ الإرسال'), ('sent', 'أُرسلت'), ('failed', 'فشلت'), ('canceled', 'أُلغيت')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_messages', to='core.tenant')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_outbound',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='whatsapp_ou_tenant__bd9e30_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAuthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_keys', to='whatsapp.whatsappaccount')),
            ],
            options={
                'db_table': 'whatsapp_auth_keys',
                'unique_together': {('account', 'key')},
            },
        ),
    ]
