# Generated by Django 5.1.15 on 2026-08-02 00:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_user_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inv_config', to='core.tenant')),
            ],
            options={
                'db_table': 'inventory_config',
            },
        ),
        migrations.CreateModel(
            name='ManualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_items', to='core.tenant')),
            ],
            options={
                'db_table': 'inventory_manual_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily', 'يومي'), ('monthly', 'شهري')], default='daily', max_length=8)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('rates', models.JSONField(blank=True, default=dict)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('assets_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('liabilities_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('previous_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('period_from', models.DateTimeField(blank=True, null=True)),
                ('period_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('orders_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.snapshot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_snapshots', to='core.tenant')),
            ],
            options={
                'db_table': 'inventory_snapshots',
                'ordering': ['-taken_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32)),
                ('group_label', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('source', models.CharField(default='auto', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.snapshot')),
            ],
            options={
                'db_table': 'inventory_snapshot_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
