# Generated by Django 5.1.15 on 2026-07-10 22:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_user_oyun_load_limit_user_price_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("same_system", "نفس النظام"),
                            ("pool", "بنك البينات"),
                            ("card_store", "متجر بطاقات"),
                            ("loader", "منفّذ يدوي"),
                        ],
                        default="card_store",
                        max_length=16,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("passive", "معطّل")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "real_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("loss_guard", models.BooleanField(default=True)),
                ("auto_update", models.BooleanField(default=False)),
                (
                    "balance_alert_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "providers",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
