# Generated by Django 5.1.15 on 2026-08-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='currency',
            field=models.CharField(default='TRY', max_length=8),
        ),
    ]
