# Generated by Django 5.1.15 on 2026-07-11 00:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_address_tenant_email_tenant_footer_html_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("sham_cash", "شام كاش"),
                            ("mtn_cash", "MTN كاش"),
                            ("syriatel_cash", "سيرياتيل كاش"),
                            ("bank", "تحويل بنكي"),
                            ("cash", "نقدي"),
                        ],
                        default="sham_cash",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "account_no",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("passive", "معطّل")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notification_enabled", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_accounts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "receiving_accounts",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "مقبول"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_notifications",
                        to="core.tenant",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payments.receivingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "payment_notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
