# Generated by Django 5.1.15 on 2026-07-31 22:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_base_currency_tenant_exchange_rates'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotification',
            name='admin_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=160)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('currency', models.CharField(choices=[('TRY', 'ليرة تركية'), ('USD', 'دولار أمريكي'), ('SYP', 'ليرة سورية'), ('EUR', 'يورو'), ('SAR', 'ريال سعودي'), ('AED', 'درهم إماراتي'), ('EGP', 'جنيه مصري')], default='TRY', max_length=8)),
                ('instructions', models.TextField(blank=True, default='')),
                ('account_box', models.TextField(blank=True, default='')),
                ('warning', models.CharField(blank=True, default='', max_length=300)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('passive', 'معطّل')], default='active', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='payments.receivingaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.tenant')),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='payments.paymentmethod'),
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('text', 'نص قصير'), ('number', 'رقم'), ('textarea', 'نص طويل'), ('select', 'قائمة اختيار'), ('image', 'رابط صورة')], default='text', max_length=10)),
                ('options', models.CharField(blank=True, default='', max_length=500)),
                ('placeholder', models.CharField(blank=True, default='', max_length=160)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='payments.paymentmethod')),
            ],
            options={
                'db_table': 'payment_method_fields',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
