# Generated by Django 5.1.15 on 2026-07-10 22:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productprice"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oyun_load_limit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("10000"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="price_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealers",
                to="catalog.pricegroup",
            ),
        ),
    ]
