# Generated by Django 5.1.15 on 2026-07-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_dealergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sms_api_key",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_provider",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sms_sender",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
