# Generated by Django 5.1.15 on 2026-07-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tenant_sms_api_key_tenant_sms_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="font",
            field=models.CharField(default="cairo", max_length=20),
        ),
    ]
