# Generated by Django 5.1.15 on 2026-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tenant_font"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_owner", "مالك المنصّة"),
                    ("tenant_admin", "صاحب المتجر"),
                    ("ana_bayi", "وكيل كبير"),
                    ("bayi", "وكيل"),
                ],
                default="bayi",
                max_length=16,
            ),
        ),
    ]
