# Generated by Django 5.1.15 on 2026-07-11 21:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sub_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sub_monthly_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sub_plan",
            field=models.CharField(
                choices=[
                    ("none", "بلا اشتراك"),
                    ("monthly", "شهري"),
                    ("yearly", "سنوي"),
                ],
                default="none",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sub_started_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="sub_yearly_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
