# Generated by Django 5.1.15 on 2026-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_platformannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="theme_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
