# Generated by Django 5.1.15 on 2026-07-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenant_theme_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='base_currency',
            field=models.CharField(default='TRY', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='exchange_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
