# Generated by Django 5.1.15 on 2026-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_base_currency_tenant_exchange_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
