# Generated by Django 5.1.15 on 2026-07-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_display_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='base_currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
