# Generated by Django 5.1.15 on 2026-07-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_flip_exchange_rate_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_debt_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='id_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
