# Generated by Django 5.1.15 on 2026-08-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_auto_debt_collection_user_id_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealerGroup',
        ),
    ]
