# Generated by Django 5.1.15 on 2026-08-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_agentpricegroup_agentproductprice_and_more'),
        ('core', '0020_user_dealer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='catalog.agentpricegroup'),
        ),
    ]
