# Generated by Django 5.1.15 on 2026-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_internal_supply_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_access_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
