# Generated by Django 5.1.15 on 2026-08-15 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_api_access_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='sub_enforce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sub_grace_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('tenants', 'أصحاب المتاجر'), ('dealers', 'الوكلاء')], max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='bell', max_length=24)),
                ('bg_color', models.CharField(default='#0f766e', max_length=24)),
                ('bg_color2', models.CharField(blank=True, default='', max_length=24)),
                ('text_color', models.CharField(default='#ffffff', max_length=24)),
                ('link_url', models.CharField(blank=True, default='', max_length=300)),
                ('link_label', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_cards', to='core.tenant')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_cards', to='core.tenant')),
            ],
            options={
                'db_table': 'home_cards',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
